// Load API key from config.js (generated by inject_key.py from your .env)
try {
  importScripts('config.js');
} catch (e) {
  console.warn('[Code AI] config.js not loaded:', e.message,
    '– Run inject_key.py to generate it.');
}

const GEMINI_URL =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent';

// ── Register context menu on every service-worker startup ────────────────────
// (onInstalled alone misses restarts, causing the item to disappear)
chrome.contextMenus.removeAll(() => {
  chrome.contextMenus.create(
    { id: 'explainCode', title: 'Explain with Code AI ✨', contexts: ['selection'] },
    () => { if (chrome.runtime.lastError) { /* already exists – ignore */ } }
  );
});

// ── Message hub ───────────────────────────────────────────────────────────────
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {

  if (request.action === 'callGemini') {
    handleGeminiCall(request.prompt)
      .then(text => sendResponse({ success: true, text }))
      .catch(err  => sendResponse({ success: false, error: err.message }));
    return true; // keep channel open for async
  }

  if (request.action === 'checkApiKey') {
    const key = resolveKey();
    sendResponse({
      hasKey:  !!key,
      preview: key ? key.slice(0, 8) + '...' : null
    });
  }
});

// ── Context-menu click ────────────────────────────────────────────────────────
chrome.contextMenus.onClicked.addListener(async (info) => {
  if (info.menuItemId !== 'explainCode' || !info.selectionText) return;

  // 1. Save selected code so the popup can read it
  await chrome.storage.local.set({
    contextCode: info.selectionText,
    contextTs:   Date.now()
  });

  // 2. Show badge on the extension icon so user knows to click it
  await chrome.action.setBadgeText({ text: '!' });
  await chrome.action.setBadgeBackgroundColor({ color: '#6C63FF' });

  // 3. Try to open the popup automatically (works in Chrome 99+)
  try {
    await chrome.action.openPopup();
  } catch (_) {
    // openPopup unavailable or failed – badge guides the user to click manually
  }
});

// ── Gemini API call ───────────────────────────────────────────────────────────
function resolveKey() {
  // config.js (from .env) takes priority
  if (typeof GEMINI_API_KEY !== 'undefined' && GEMINI_API_KEY) return GEMINI_API_KEY;
  return null;
}

async function handleGeminiCall(prompt) {
  const key = resolveKey();

  if (!key) {
    throw new Error(
      'API key not found. Run inject_key.py to generate config.js from your .env, ' +
      'then reload the extension.'
    );
  }

  const res = await fetch(`${GEMINI_URL}?key=${key}`, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents:         [{ parts: [{ text: prompt }] }],
      generationConfig: { temperature: 0.3, maxOutputTokens: 8192 }
    })
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `Gemini API error ${res.status}`);
  }

  const data = await res.json();
  return (
    data.candidates?.[0]?.content?.parts?.[0]?.text ||
    'No response returned from Gemini.'
  );
}
