// Auto-generated by inject_key.py — do NOT edit manually.
// Re-run `python inject_key.py` after changing your .env
// WARNING: do NOT commit this file — it contains your API key.
var GEMINI_API_KEY = "<GEMINI API KEY HERE>";
