"""
Reads GEMINI_API_KEY from the project .env and writes it into config.js
so the Chrome extension can use it without manual entry in the UI.

Usage (run from any directory):
    python chrome-extension/inject_key.py
  or, from inside chrome-extension/:
    python inject_key.py
"""
import os
import sys

HERE   = os.path.dirname(os.path.abspath(__file__))
ENV    = os.path.join(HERE, '..', '.env')
CONFIG = os.path.join(HERE, 'config.js')


def parse_env(path: str) -> dict:
    env = {}
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, val = line.partition('=')
            env[key.strip()] = val.strip().strip('"').strip("'")
    return env


def main():
    if not os.path.exists(ENV):
        sys.exit(f'ERROR: .env not found at {ENV}')

    env = parse_env(ENV)
    key = env.get('GEMINI_API_KEY', '')

    if not key:
        sys.exit('ERROR: GEMINI_API_KEY is missing or empty in .env')

    js = f"""// Auto-generated by inject_key.py — do NOT edit manually.
// Re-run `python inject_key.py` after changing your .env
// WARNING: do NOT commit this file — it contains your API key.
var GEMINI_API_KEY = "{key}";
"""
    with open(CONFIG, 'w', encoding='utf-8') as f:
        f.write(js)

    preview = key[:8] + '...'
    print(f'OK  config.js written  (key: {preview})')
    print(f'    Path: {CONFIG}')


if __name__ == '__main__':
    main()
